import {
  Activity03Icon,
  AddCircleIcon,
  AiBrain01Icon,
  ArrowLeftRightIcon,
  Attachment01Icon,
  AudioWave01Icon,
  Brain02Icon,
  BrowserIcon,
  BubbleChatAddIcon,
  BubbleChatTemporaryIcon,
  BulbIcon,
  Calendar03Icon,
  CommandIcon,
  Comment01Icon,
  CursorInfo02Icon,
  CursorPointer01Icon,
  DashboardSpeed02Icon,
  DashedLineCircleIcon,
  FileViewIcon,
  Flag01Icon,
  FolderLibraryIcon,
  GitBranchIcon,
  HelpCircleIcon,
  Hold05Icon,
  InputLongTextIcon,
  InputShortTextIcon,
  LaptopIcon,
  Layers01Icon,
  LayoutThreeColumnIcon,
  LayoutTopIcon,
  LayoutTwoColumnIcon,
  LeftToRightListBulletIcon,
  LeftToRightListDashIcon,
  Link01Icon,
  Loading03Icon,
  Menu01Icon,
  Message01Icon,
  MessageEdit01Icon,
  MessageMultiple01Icon,
  Mic01Icon,
  MinusSignIcon,
  MousePointerClickIcon,
  Notification01Icon,
  PanelRightIcon,
  PuzzleIcon,
  Route01Icon,
  Settings01Icon,
  Share08Icon,
  SidebarLeftIcon,
  Square01Icon,
  Tag01Icon,
  TextFontIcon,
  TextIcon,
  TypeCursorIcon,
  UserAccountIcon,
  UserCircleIcon,
} from "@hugeicons/core-free-icons"
import type { IconSvgElement } from "@hugeicons/react"

// Each registry item's mark, read by its gallery card and its docs entry, so
// the two always show the same one. A new item with a card gets a line here.
const ITEM_ICONS: Record<string, IconSvgElement> = {
  "add-menu": AddCircleIcon,
  attachments: Attachment01Icon,
  avatar: UserCircleIcon,
  badge: Tag01Icon,
  "branches-menu": GitBranchIcon,
  breadcrumb: Route01Icon,
  button: MousePointerClickIcon,
  chat: Hold05Icon,
  command: CommandIcon,
  composer: MessageEdit01Icon,
  "date-divider": Calendar03Icon,
  dialog: Square01Icon,
  "dictate-button": Mic01Icon,
  "editable-title": TextFontIcon,
  empty: DashedLineCircleIcon,
  "file-preview": FileViewIcon,
  "help-menu": HelpCircleIcon,
  "history-buttons": ArrowLeftRightIcon,
  "hover-card": CursorPointer01Icon,
  input: TextIcon,
  "input-group": InputShortTextIcon,
  marker: Flag01Icon,
  menu: Menu01Icon,
  message: Message01Icon,
  meter: DashboardSpeed02Icon,
  "model-selector": AiBrain01Icon,
  "nav-bars": LeftToRightListDashIcon,
  panels: LayoutThreeColumnIcon,
  "plugin-selector": PuzzleIcon,
  popover: Layers01Icon,
  "project-selector": FolderLibraryIcon,
  "quick-chat": BubbleChatAddIcon,
  reasoning: Brain02Icon,
  resizable: LayoutTwoColumnIcon,
  separator: MinusSignIcon,
  "settings-dialog": Settings01Icon,
  "share-dialog": Share08Icon,
  sheet: PanelRightIcon,
  sidebar: SidebarLeftIcon,
  skeleton: Loading03Icon,
  sources: Link01Icon,
  status: Activity03Icon,
  "stream-text": TypeCursorIcon,
  suggestions: BulbIcon,
  tabs: BrowserIcon,
  "temporary-chat-toggle": BubbleChatTemporaryIcon,
  textarea: InputLongTextIcon,
  "thinking-indicator": Loading03Icon,
  thread: MessageMultiple01Icon,
  "thread-transcript": LeftToRightListBulletIcon,
  toast: Notification01Icon,
  toolbar: LayoutTopIcon,
  tooltip: Comment01Icon,
  "tooltip-icon-button": CursorInfo02Icon,
  "user-menu": UserAccountIcon,
  waveform: AudioWave01Icon,
  "work-in-menu": LaptopIcon,
}

export { ITEM_ICONS }
